export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const SHOW_ITEM_QUANTITY = 'SHOW_ITEM_QUANTITY';
